[workspace]
members = ["oxide-core", "oxide-pkg", "oxide-repo-server"]

[workspace.package]
version = "0.0.1"
authors = ["Liz Ainslie"]
description = "A short description of my package"
documentation = "https://example.com/bar"
edition = "2021"