[workspace]
members = ["oxide_pkg", "oxide_repo_server", "oxide_repo_server/migration"]

[workspace.package]
version = "0.0.1"
authors = ["Liz Ainslie"]
description = "A decentralized package management tool from the future"
documentation = "https://example.com/bar"
edition = "2021"