[package]
name = "oxide_core"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }